CREATE TABLE IF NOT EXISTS convos.client_records (
  client_user_id    INT PRIMARY KEY REFERENCES convos.users(id) ON DELETE CASCADE,
  consentimiento    BOOL NOT NULL DEFAULT FALSE,
  consentimiento_at TIMESTAMPTZ,
  datos             JSONB NOT NULL DEFAULT '{}',
  created_at        TIMESTAMPTZ DEFAULT NOW(),
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA convos TO convos_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA convos TO convos_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA convos GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO convos_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA convos GRANT USAGE,SELECT,UPDATE ON SEQUENCES TO convos_app;
